### PR TITLE
Code Clean up

### PR DESCRIPTION
**Pull request by azzy9**
There are a couple of commits that look out of place, that is due to me messing up with github desktop.
Started to clean up code and added setting to select quality if the user wishes.

### CODE REVIEW

**Comment by ilikenwf** [comment]
Thank you!

**Comment by ilikenwf** [comment]
So after a brief test it appears that search is broken, it also appears the folder icons have disappeared (not that that part matters all that much).

Otherwise, playback and favorites, the categories do still work properly.

I'll look if I get a chance but I bet that we're just missing a renamed reference somewhere after your adjustment to how search is called.

**Comment by ilikenwf** [comment]
...also thanks for looking into this, there's a lot of duplicated code in the original.

**Comment by ilikenwf** [comment]
And in the case of search, it throws some error and never even opens up a prompt, let me find the message:

```
.kodi/addons/plugin.video.rumble.matrix/main.py", line 145, in search_menu
                                                       addDir('[B]'+__language__(30100)+'[/B]',BASE_URL+'/search/video?q='.encode('utf8'),2,search_icon,'','','video')
                                                   TypeError: can only concatenate str (not "bytes") to str
                                                   -->End of Python script error report<--

```

**Comment by ilikenwf** [comment]
I think it's the comma there where a + should be.

**Comment by ilikenwf** [comment]
Apparently not...

I dabble in many language, expert in only a few, python is not one I'm an expert in...

**Comment by azzy9** [comment]
Sorry about that, it is due to the encode where it is no longer needed, will make a PR when I can then look into the icons

**Pull request merged**
