### PR TITLE
Fix search & icons

### PR DESCRIPTION
**Pull request by azzy9**

### CODE REVIEW

**Comment by azzy9** [comment]
This PR fixes the issue with search & the missing icons issue

**Comment by ilikenwf** [comment]
Does it also fix the broken regex for livestreams? I ran into that, will test after merging to testing and then hopefully push.

Sorry, didn't get an email from github.

**Comment by ilikenwf** [comment]
One of the commits from #2 has apparently broken the resolver/scraper regex for specifically livestream videos. Otherwise the things you fixed look good @azzy9 

```
022-12-02 18:08:17.676 T:66270   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'replace'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.rumble.matrix/main.py", line 587, in <module>
                                                       main()
                                                     File "/home/kodi/.kodi/addons/plugin.video.rumble.matrix/main.py", line 559, in main
                                                       play_video(name, url, iconimage, play)
                                                     File "/home/kodi/.kodi/addons/plugin.video.rumble.matrix/main.py", line 307, in play_video
                                                       url = resolver(url)
                                                     File "/home/kodi/.kodi/addons/plugin.video.rumble.matrix/main.py", line 302, in resolver
                                                       return mediaURL.replace('\/', '/')
                                                   AttributeError: 'NoneType' object has no attribute 'replace'
                                                   -->End of Python script error report<--
```

**Comment by azzy9** [comment]
That error is due to no media URL being found, I have not changed any regex so not sure what is happened here? Do you have a URL for a live stream that I could use to test? I don't know if they have 24/7 live streams on rumble like they do on youtube & odysee

**Comment by azzy9** [comment]
Just realised there is a live tab on the site, so will use one of those

**Comment by ilikenwf** [comment]
> That error is due to no media URL being found, I have not changed any regex so not sure what is happened here? Do you have a URL for a live stream that I could use to test? I don't know if they have 24/7 live streams on rumble like they do on youtube & odysee

I think I may have been having a DNS issue unless you can confirm the issue between the two branches?

**Comment by azzy9** [comment]
Found the error, just doing some more work on my testing branch then will do a PR

**Pull request merged**
