### PR TITLE
Move Language strings

### PR DESCRIPTION
**Pull request by azzy9**
Move strings for each language into their own files

### CODE REVIEW

**Comment by ilikenwf** [comment]
Looks good to me! Thank you!

I didn't bother cleaning this up, including a lot of the nasty duplicated code, as when I did it, it was more a "I want to watch a livestream now" type thing.

I just figured it worth sharing.

**Comment by azzy9** [comment]
ty for merging, will do some more PR's for clean-up when I get around to it

**Comment by ilikenwf** [comment]
Works for me! I'm wondering if it was obfuscated to "protect" it or to hide how spaghetti some of the code is...

**Comment by azzy9** [comment]
maybe to hide the tracking they put in, which I noticed you removed

**Comment by ilikenwf** [comment]
Yes, I'm not a fan of that kind of thing...

Also in testing, after merging, I notice a few of the labels in the addon are missing so we may need to go back and fix them - I may move current master to a testing branch for now and revert on master for anyone looking to use the addon.

I've got to work or I'd fix it this minute.

**Comment by ilikenwf** [comment]
Your change is merged in the testing branch for now.

**Comment by azzy9** [comment]
Just downloaded from the testing branch and installed it, working all fine for me. what language is your kodi installation if you don't mind me asking. Mine is en_gb, the resource file is that too but the languages should fallback to that if thier language doesn't exist.
Also to note, the plugin will need to be installed by kodi rather than copy and pasting it for it to use the plugin's string files (I made that mistake in the past)

**Comment by ilikenwf** [comment]
en_US - should I just copy the en_GB strings or would Kodi select the nearest neighbor?

**Comment by azzy9** [comment]
Kodi should fallback to en_gb, i'll do some testing

**Comment by ilikenwf** [comment]
I'll test properly updating this time too...haha

**Comment by ilikenwf** [comment]
That fixed it, I'll merge back to master....sorry for being half awake!

**Comment by azzy9** [comment]
not a problem :)

**Pull request merged**
